// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5cuqDBpynEJpzoDkxZbswcg53GeY7-Nw',
    appId: '1:1026081387704:web:208b229a37f7c135c0b04d',
    messagingSenderId: '1026081387704',
    projectId: 'meditation-maker',
    authDomain: 'meditation-maker.firebaseapp.com',
    storageBucket: 'meditation-maker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRaeMmzSdja2SskVnFYvzb_prJew0LgBY',
    appId: '1:1026081387704:android:783719f35210a1e7c0b04d',
    messagingSenderId: '1026081387704',
    projectId: 'meditation-maker',
    storageBucket: 'meditation-maker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk84z0Ny8jFMGY1beQUP4_4phDV2Ux7F4',
    appId: '1:1026081387704:ios:4fc87d8b485ca782c0b04d',
    messagingSenderId: '1026081387704',
    projectId: 'meditation-maker',
    storageBucket: 'meditation-maker.appspot.com',
    iosClientId: '1026081387704-6lg9400hpk5mnirftdktcpb6a3a2nbcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditationMaker',
  );
}
